### ISSUE TITLE
No commits since January

### ISSUE THREAD

**Issue by puckey** [paperjs/paperjs.github.io#10]
It looks like there haven't been any nightly build commits here since January..

**Comment by lehni** [comment]
Yes they're here now:

https://github.com/paperjs/paper.js/tree/prebuilt/module
https://github.com/paperjs/paper.js/tree/prebuilt/dist

The site is not reflecting this yet, as i haven't found the time to adjust things. Hopefully once v0.10.0 is out, whenever I find the time for rolling that out.
